### ISSUE TITLE
Is Ionic / Phonegap OK with Flare use?

### ISSUE THREAD

**Issue by bill-rousseau** [CiscoDevNet/flare#3]
I'm building a Ionic-based app, but I only found native Java/Swift Flare implementations in the docs.

Can I use Flare API with this kind of architecture? I've seen a Javascript section in the docs, but I'm not sure if I can do as if it was a webapp in that case.

**Comment by azamlerc** [comment]
Hi Bill,

We have Flare sample code available for a variety of platforms, but different platforms have different levels of functionality. 

The JavaScript sample code supports the realtime messages, and is useful for example for creating interactive displays for things. 

The native Swift and Java code support detecting Bluetooth beacons, and is useful for user devices. I don't think it would be convenient to use the JavaScript code for detecting beacons.

Cheers,
Andrew
